### ISSUE TITLE
Export color and height options to CSS

### ISSUE THREAD

**Issue by eyalroth** [dmetivier/gatsby-plugin-page-progress#18]
It would be preferable to set the color and height of the progress var via CSS, as these are clearly style-oriented properties. This would be helpful in matching the color of the progress bar to the rest of the site's theme.

Another minor benefit is when trying different configurations in development (`gatsby develop`), as moving these options to CSS instead of `gatsby-config.js` would not require a restart of the development server for changes to take effect.

**Comment by dmetivier** [comment]
See #21
